[package]
name = "logflume"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.22"
core_affinity = "0.5.10"
log = { version = "0.4.17", features = ["std"] }
crossbeam-channel = "0.5"
lockfree = "0.5.1"

[dev-dependencies]
log4rs = "1.1.1"

[[example]]
name = "basic"
